name: "Build and Sync Homepage"
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - ./projects/homepage/client/**

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "eu-west-1"

jobs:
  sync:
    name: "Build and Sync Homepage"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projects/homepage/client
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: npm ci
        run: npm ci

      - name: npm build
        run: npm run build

      - name: s3 sync
        run: aws s3 sync dist/ s3://628602948023-learnprogramming --delete

      - name: invalidate distribution
        run: aws cloudfront create-invalidation --distribution-id EVF5M3I81ONIU --paths "/*"
